package windows

import (
	updatenative "github.com/tinyrange/trex/windows/update/native"
	"go.starlark.net/starlark"
)

// Builtins returns the Windows format and construction functions exposed by
// the optional Starlark frontend.
func Builtins() starlark.StringDict {
	functions := map[string]func(*starlark.Thread, *starlark.Builtin, starlark.Tuple, []starlark.Tuple) (starlark.Value, error){
		"memory_image":                memoryImageBuiltin,
		"reactos_record":              reactOSRecordBuiltin,
		"ne_fastboot":                 windowsNEFastBootBuiltin,
		"setver":                      windowsSetverBuiltin,
		"win9x_vxd_unpack":            win9xVXDUnpackBuiltin,
		"win9x_vxd_library":           win9xVXDLibraryBuiltin,
		"win9x_vxd_library_members":   win9xVXDLibraryMembersBuiltin,
		"pdb":                         windowsPDBBuiltin,
		"symbol_server":               windowsSymbolServerBuiltin,
		"hive":                        hiveBuiltin,
		"module_sources":              moduleSourcesBuiltin,
		"clone_file_entries":          cloneFileEntriesBuiltin,
		"registration_expand":         registrationExpandBuiltin,
		"registry_partition":          registryPartitionBuiltin,
		"registry_children":           registryChildrenBuiltin,
		"assembly_manifest":           assemblyManifestBuiltin,
		"certificate":                 certificateBuiltin,
		"signing_identity":            signingIdentityBuiltin,
		"test_signing_identity":       testSigningIdentityBuiltin,
		"pe_sign":                     peSignBuiltin,
		"csp_registrations":           cspRegistrationsBuiltin,
		"font_names":                  fontNamesBuiltin,
		"icon":                        windowsIconBuiltin,
		"pe":                          peObjectBuiltin,
		"pe32_executable":             pe32ExecutableBuiltin,
		"hive_from_patches":           hiveFromPatchesBuiltin,
		"creg_from_patches":           cregFromPatchesBuiltin,
		"creg_compare":                cregCompareBuiltin,
		"creg_keys":                   cregKeysBuiltin,
		"creg_patches":                cregPatchesBuiltin,
		"hive_keys":                   hiveKeysBuiltin,
		"hive_patches":                hivePatchesBuiltin,
		"hives_from_inf":              hivesFromINFBuiltin,
		"inf_patches":                 infPatchesBuiltin,
		"inf":                         infBuiltin,
		"msc_snapins":                 mscSnapinsBuiltin,
		"minidump":                    minidumpBuiltin,
		"mof":                         mofBuiltin,
		"wmi_repository":              wmiRepositoryBuiltin,
		"pkcs7_certificates":          pkcs7CertificatesBuiltin,
		"catalog_members":             catalogMembersBuiltin,
		"catalog_hash":                catalogHashBuiltin,
		"patch_hive":                  patchHiveBuiltin,
		"hive_log":                    hiveLogBuiltin,
		"empty_event_log":             emptyEventLogBuiltin,
		"event_log":                   eventLogBuiltin,
		"sid_string":                  sidStringBuiltin,
		"selfreg_patches":             selfregPatchesBuiltin,
		"shortcut":                    shortcutBuiltin,
		"internet_shortcut":           internetShortcutBuiltin,
		"utf16_strings":               utf16StringsBuiltin,
		"delta_info":                  deltaInfoBuiltin,
		"delta_apply":                 deltaApplyBuiltin,
		"delta_trace":                 deltaTraceBuiltin,
		"container_index":             containerIndexBuiltin,
		"servicing_graph":             servicingGraphBuiltin,
		"servicing_plan":              servicingPlanBuiltin,
		"assembly_registry_data":      assemblyRegistryDataBuiltin,
		"wow64_registry_key":          wow64RegistryKeyBuiltin,
		"kernel_dump_header":          kernelDumpHeaderBuiltin,
		"state_repository_dictionary": stateRepositoryDictionaryBuiltin,
		"state_repository_hash":       stateRepositoryHashBuiltin,
		"pri_sections":                priSectionsBuiltin,
		"pri_schema":                  priSchemaBuiltin,
		"pri_resource_candidates":     priResourceCandidatesBuiltin,
		"mrm_literal_reference":       mrmLiteralReferenceBuiltin,
		"mrm_missing_file_reference":  mrmMissingFileReferenceBuiltin,
		"mrm_index_reference":         mrmIndexReferenceBuiltin,
		"dmr_package_resources":       dmrPackageResourcesBuiltin,
		"dmr_application_resources":   dmrApplicationResourcesBuiltin,
		"dmr_target_platform":         dmrTargetPlatformBuiltin,
		"dmr_graph":                   dmrGraphBuiltin,
		"dmr_applications":            dmrApplicationsBuiltin,
		"dmr_globalization":           dmrGlobalizationBuiltin,
		"dmr_package_security":        dmrPackageSecurityBuiltin,
		"dmr_alternate_path":          dmrAlternatePathBuiltin,
		"dmr_mutable_paths":           dmrMutablePathsBuiltin,
		"dmr_trailer":                 dmrTrailerBuiltin,
		"dmr_container":               dmrContainerBuiltin,
		"update_media":                updatenative.MediaBuiltin,
		"update_catalog":              updatenative.CatalogBuiltin,
	}
	result := make(starlark.StringDict, len(functions))
	for name, function := range functions {
		result[name] = starlark.NewBuiltin(name, function)
	}
	return result
}
