"""Portable SCS workspace edits, file sharing and in-process project build."""
load("//tests:testing.star", "case", "equal", "true", "raises", "suite")

def test_project_workflow():
    repo = scs.memory(max_bytes = 4 * 1024 * 1024)
    source = repo.empty()
    source.write_file("main.c", "int main(void) { return 1; }\n")
    source.publish("source")
    old = source.open_file("main.c")
    captured = source.view()
    project = source.fork()
    patched = old.splice(24, 1, "0")
    equal(old.read(), "int main(void) { return 1; }\n")
    project.write_file("main.c", patched)
    project.write_file("copy.c", old)
    equal(project.read_file("copy.c"), old.read())
    equal(captured.read_file("main.c"), old.read())
    raises(captured.write_file, ["x", "denied"], message = "read-only")
    compiled = renvo.cc(source = project, input = "main.c", target = "windows/386", arena_size = 1024 * 1024)
    true(compiled.ok)
    project.write_file("app.exe", compiled.binary)
    project.publish("build")
    artifact = repo.file()
    repo.close()
    reopened = scs.memory(artifact, max_bytes = 4 * 1024 * 1024)
    saved = reopened.checkout("build")
    equal(saved.open_file("app.exe").bytes(0, 2), b"MZ")
    equal(saved.read_file("main.c"), "int main(void) { return 0; }\n")
    equal(reopened.checkout("source").read_file("main.c"), "int main(void) { return 1; }\n")
    reopened.close()

def test_no_implicit_publication():
    repo = scs.memory(max_bytes = 1024 * 1024)
    repo.empty().write_file("unpublished", "not a ref")
    reopened = scs.memory(repo.file(), max_bytes = 1024 * 1024)
    equal(reopened.refs(), {})
    reopened.close()
    repo.close()

TEST_SUITE = suite("scs", [case("project_workflow", test_project_workflow), case("no_implicit_publication", test_no_implicit_publication)])
