package starlarkfrontend

import "testing"

func TestMemoryStructures(t *testing.T) {
	architectureScript(t, `
load("@stdlib//inspect:memory.star", "read_structure", "walk_list", "read_list")
def check(value):
    if not value:
        fail("memory assertion failed")
def run():
    b = binary.builder()
    b.reserve(128)
    b.patch_u32le(16, 32)
    b.patch_u32le(20, 32)
    b.patch_u32le(32, 16)
    b.patch_u32le(36, 16)
    b.patch_u32le(40, 123)
    space = windows.memory_image(b.file())
    layout = {"pid": (8, "uint", 4)}
    r = read_list(space, 16, layout)
    check(r["complete"] and r["value"] == [{"address": 32, "fields": {"pid": 123}}])
    check(walk_list(space, 16, link_offset=8)["value"] == [24])
    check(space.read(40,4) == b"\x7b\x00\x00\x00")
    check(space.view(40,4).bytes() == space.read(40,4))
    check(not space.probe(128,1).complete)
    sparse = windows.memory_image(b.file(), ranges=[(16,16,8)])
    check(not walk_list(sparse,16)["complete"])
    check(not sparse.probe(0,1).complete and sparse.probe(0,1).fault.kind == "not-captured")
    b.patch_u32le(36, 0)
    space = windows.memory_image(b.file())
    check(not walk_list(space,16)["complete"])
    b.patch_u32le(16,16)
    b.patch_u32le(20,16)
    space = windows.memory_image(b.file())
    check(walk_list(space,16)["complete"] and walk_list(space,16)["value"] == [])
    b.patch_u16le(64,2)
    b.patch_u16le(66,2)
    b.patch_u32le(68,80)
    b.patch_u16le(80,65)
    space = windows.memory_image(b.file())
    check(read_structure(space,64,{"name":(0,"unicode",8)})["value"]["name"] == "A")
    b.patch_u16le(64,3)
    space = windows.memory_image(b.file())
    check(not read_structure(space,64,{"name":(0,"unicode",8)})["complete"])
    check(read_structure(space,80,{"name":(0,"cstring",2)})["value"]["name"] == "A")
    x = space.address_space(0)
    check(not x.translate(0).mapped and x.translate(0).fault.kind == "not-present")
    b.patch_u32le(16,32)
    b.patch_u32le(20,48)
    b.patch_u32le(32,48)
    b.patch_u32le(36,16)
    b.patch_u32le(48,16)
    b.patch_u32le(52,32)
    space = windows.memory_image(b.file())
    check(walk_list(space,16)["value"] == [32,48])
    limited = walk_list(space,16,maximum=1)
    check(not limited["complete"] and limited["value"] == [32] and limited["fault"]["kind"] == "limit")
    partial = read_structure(space,120,{"ok":(0,"uint",4), "missing":(8,"uint",4)})
    check(not partial["complete"] and partial["value"] == {"ok":0} and partial["fault"]["kind"] == "not-captured")
    empty = windows.memory_image(b.file(),ranges=[])
    check(not empty.probe(0,1).complete)
run()
`)
}
