package starlarkfrontend

import (
	"fmt"
	binaryapi "github.com/tinyrange/trex/binary"
	"strings"
)

// Each native entry point needs an explicit contract. Do not replace missing
// descriptions with boilerplate: generation must fail until the API is documented.
var nativeStarlarkDescriptions = map[string]string{
	"windows.memory_image":              "Borrows a file as a read-only physical capture. Optional ranges map (physical_start, file_offset, size); omitted ranges cover the whole file, while an empty list captures nothing. Gaps remain unavailable, not zero-filled. Keep the source unchanged while views exist; this does not parse crash dumps or discover RAM ranges.",
	"windows.icon":                      "Selects an icon image from an ICO, PE or NE file using its index and requested dimensions. Returns image bytes with actual dimensions, bit depth and resource identity; it does not launch or render the executable.",
	"archive.ar":                        "Parses a Unix ar archive and returns ordered member metadata and file views. find(name, occurrence) distinguishes duplicate member names.",
	"archive.cab":                       "Parses a Microsoft Cabinet file and exposes its members as file views. Folder decompression is shared when caching is enabled, so several entries in one compressed folder need not decode it repeatedly.",
	"archive.cab_set":                   "Opens related Cabinet files as one set, resolving files and compressed data that span cabinet boundaries. The caller supplies the cabinet files; the parser does not search host directories.",
	"archive.installer":                 "Recognizes a supported installer container, including supported embedded payloads, and returns an inspection object with files and a declarative installation plan. It does not run the installer or apply that plan.",
	"archive.installer_probe":           "Inspects a candidate installer and returns detection details and diagnostics as a dictionary. Use it to distinguish unsupported packaging from a recognized payload before requesting a full plan.",
	"archive.installscript":             "Parses compiled InstallShield InstallScript into functions, callbacks, calls and effects. The result supports bounded evaluation of the modeled script semantics; parsing does not execute a host installer.",
	"archive.installshield":             "Combines an InstallShield header, cabinet files and optional externally supplied files into an archive view. Exposes file groups, components and shortcuts needed for installation planning.",
	"archive.kwaj":                      "Decodes a Microsoft KWAJ-compressed input into a file, enforcing the decoded-size bound. Use kwaj_info when the header's original name and compression method are also needed.",
	"archive.kwaj_info":                 "Returns the decoded KWAJ file together with its original name, method and compressed/decoded sizes. This preserves wrapper metadata that archive.kwaj omits.",
	"archive.sevenzip":                  "Parses a 7-Zip archive into member file views with bounded entry count, metadata and decoder dictionary size. Unsupported compression methods fail explicitly.",
	"archive.sfp":                       "Parses an SFP installer archive and exposes member paths, timestamps, stored sizes and payload file views. It does not install the contents.",
	"archive.szdd":                      "Decodes the legacy Microsoft SZDD single-file compression format and returns a file. maximum bounds decoded output rather than the compressed input alone.",
	"archive.tar":                       "With a directory, serializes its entries into tar bytes, optionally compressed. With a file, parses a tar archive and preserves ordered entries, metadata and duplicate-name occurrences.",
	"archive.wim":                       "Parses a Windows Imaging Format archive and exposes its image contents through file views. The archive reader handles its supported compression internally without mounting an image.",
	"archive.xz":                        "Decodes an XZ stream into a file, rejecting decoder dictionaries above max_dictionary. This unwraps compression; it does not interpret an archive contained in the decoded bytes.",
	"archive.zip":                       "Parses a ZIP archive and exposes its member files. Reads decompress the selected entries without extracting them into a host directory.",
	"binary.annotate":                   "Wraps a file with caller-supplied attributes while retaining its bytes. Use this to attach construction metadata without rebuilding the file's contents.",
	"binary.base64":                     "Encodes binary input as a Base64 string. url selects the URL-safe alphabet, padding controls trailing equals signs, and maximum bounds encoded output.",
	"binary.bits":                       "Creates a stateful bit reader over binary input. Its read, peek, drop and align operations consume or inspect bits in the selected bit order.",
	"binary.builder":                    "Creates a bounded mutable byte builder. Append encoded values, reserve or patch regions, then obtain bytes or a file; capacity is an allocation hint and limit bounds growth.",
	"binary.concat":                     "Returns a lazy file formed by concatenating binary parts in order. Unlike bytes_concat, it need not materialize the complete result at construction time.",
	"binary.cursor":                     "Creates a sequential byte reader at the selected offset. Scalar reads and bytes(size) advance its position; seek, skip and align change that position explicitly.",
	"binary.decode":                     "Decodes a hex, Base64 or unpadded URL-safe Base64 string into bytes. This is the inverse of binary.hex/base64, not a character-set decoder; use binary.text for text.",
	"binary.encode":                     "Encodes a string into bytes using the selected character encoding. nul appends an encoding-appropriate terminator; binary.text performs the reverse conversion.",
	"binary.extents":                    "Constructs a file of the requested logical size from supplied byte extents. Unpopulated ranges read as zero, allowing sparse image layouts without allocating every logical byte.",
	"binary.hex":                        "Encodes binary input as lowercase hexadecimal text, with two characters per input byte. maximum bounds the encoded result; use top-level hex to format an integer.",
	"binary.layout":                     "Compiles a fixed-size binary layout from a format string and optional field names. The returned value encodes records or decodes a source at a byte offset.",
	"binary.replace":                    "Returns bytes with up to count non-overlapping occurrences of old replaced by new; count=-1 replaces all. old must be nonempty and maximum bounds the result.",
	"binary.strings":                    "Scans binary input for printable ASCII or UTF-16LE strings of at least minimum characters. Returns string values, not offsets or a decoded version of the entire file.",
	"binary.text":                       "Decodes binary input into a string using the selected character encoding. nul requests terminator-aware decoding; maximum bounds input size.",
	"binary.view":                       "Creates a bounded random-access byte view, optionally over a source slice. It supports byte search, comparisons and further slicing without requiring the entire source to be copied.",
	"binary.xml":                        "Parses XML into namespace-aware immutable document and node values. Size, depth and node-count limits bound parsing; with_root/with_children/with_text create edited values for serialization.",
	"block.cache":                       "Adds a bounded read-through chunk cache to a block device. It speeds repeated reads but is not a writable overlay or a persistent image cache.",
	"block.device":                      "Wraps a file as a block device with declared logical and physical block geometry. Writable mode requires a source that supports writes; it does not implicitly add copy-on-write storage.",
	"block.nbd":                         "Creates an NBD protocol server for a block device. serve(channel) processes requests over a supplied byte channel; constructing the server does not open a listening socket.",
	"block.overlay":                     "Creates a bounded writable copy-on-write layer over a base block device. Writes affect the overlay, leaving the base unchanged; max_dirty_bytes bounds retained changes.",
	"block.view":                        "Returns a read-only file view of a live block device. Later device changes remain visible through the view; it is not an immutable snapshot.",
	"bytes_concat":                      "Materializes a list of binary values into one bytes value, preserving order. Use binary.concat when a lazy file composition is preferable.",
	"clock.monotonic":                   "Returns seconds from the runtime's monotonic clock. Subtract readings to time work; the value is not a calendar timestamp.",
	"clock.profiler":                    "Creates a profiler for named spans, counters and measured calls. Its snapshots and reports summarize work explicitly recorded through this profiler.",
	"clock.unix":                        "Returns the runtime clock's current Unix timestamp in seconds. Use clock.monotonic rather than calendar time to measure durations.",
	"clock.utc":                         "Converts an integer Unix timestamp into a dictionary of UTC year, month, weekday, day, hour, minute, second and millisecond fields. Weekday uses Sunday=0; this converts a supplied time rather than reading the current clock.",
	"crypto.aes":                        "Encrypts or decrypts complete 16-byte AES blocks in CBC or ECB mode, returning bytes without adding or removing padding. CBC uses a zero IV when none is supplied; callers implementing a protocol must provide its required IV and authentication.",
	"crypto.checksum":                   "Returns an integer Adler-32 or supported CRC-32 checksum for binary input. These checksums detect accidental changes; they are not cryptographic authentication.",
	"crypto.constant_time_equal":        "Compares two binary values using a constant-time comparison for equal-length inputs. Returns a boolean; differing lengths are not hidden.",
	"crypto.des":                        "Encrypts or decrypts complete 8-byte blocks with an 8-byte DES key. Supplying an IV selects CBC; otherwise blocks are processed independently. This legacy compatibility primitive adds no padding or authentication.",
	"crypto.deterministic":              "Derives a reproducible byte sequence from a seed using domain-separated counter hashes. Equal seed, algorithm and size produce equal output; it is not an entropy source.",
	"crypto.hash":                       "Returns raw digest bytes for binary input using MD4, MD5, SHA-1, SHA-224, SHA-256, SHA-384 or SHA-512. Legacy algorithms are provided for format compatibility, not as recommendations for new security protocols.",
	"crypto.hash_blocks":                "Advances a supplied SHA-1 or SHA-256 compression state over complete blocks and returns the updated state. It does not perform message padding or finalization; use crypto.hash for a complete digest.",
	"crypto.hasher":                     "Creates a mutable incremental hash state. update(value) feeds input, sum() reads the current digest without resetting, and reset() starts a new message.",
	"crypto.hmac":                       "Computes an HMAC over binary input using the supplied key and hash algorithm. Returns raw authentication bytes rather than hexadecimal text.",
	"crypto.mod_exp":                    "Computes base raised to exponent modulo modulus from byte-encoded nonnegative operands. byte_order applies to inputs and output; the result is padded to the modulus byte width.",
	"crypto.mod_inverse":                "Returns the multiplicative inverse of an integer modulo a positive modulus, or None when no inverse exists. Operands are bounded to 16384 bits; this arithmetic operation is not a constant-time cryptographic protocol.",
	"crypto.mod_mul":                    "Multiplies byte-encoded nonnegative operands modulo a byte-encoded modulus. The selected byte order is preserved and the result has the modulus's byte width.",
	"crypto.random":                     "Returns the requested number of bytes from the runtime's cryptographic randomness source. Unlike crypto.deterministic, repeated calls are not reproducible.",
	"crypto.rc4":                        "Applies the RC4 stream cipher to binary input using a fresh state initialized from key. Encryption and decryption use the same operation; this unauthenticated legacy primitive is for compatibility.",
	"crypto.xtea":                       "Encrypts or decrypts complete 8-byte XTEA blocks with a 16-byte key and the selected word byte order. Returns bytes without padding or authentication.",
	"database.ese":                      "Parses an Extensible Storage Engine database into inspectable tables and records. It is a file-format reader, not a host ESE engine or SQL connection.",
	"database.ese_build":                "Builds an ESE database file from declarative tables, optionally controlling database page allocation and sort data. Construction stays in memory.",
	"database.sqlite":                   "Parses a SQLite database, optionally applying a supplied WAL view, and exposes schema and table rows. It does not execute arbitrary SQL through a host SQLite process.",
	"database.sqlite_build":             "Builds a SQLite database file from declarative schema and row data. The output can be embedded in an image without invoking a host database engine.",
	"debug.disassemble":                 "Decodes machine-code bytes into instruction records at a supplied base address. Supports the listed 16-, 32- and 64-bit x86 modes; count bounds returned instructions.",
	"debug.gdb":                         "Connects a GDB remote-protocol session over an existing byte channel. The returned session controls the target and reads structured stops, registers and memory without launching a host debugger.",
	"debug.select":                      "Waits until one of the supplied selectable values is ready, returning that value, or None on timeout. Read the event from the returned source separately; selection itself does not consume the event.",
	"digest":                            "Hashes a file, string or bytes value and returns raw digest bytes, not hexadecimal text. The default algorithm is SHA-256.",
	"directory":                         "Creates an empty, mutable in-memory directory tree. Add files and metadata to it before passing it to a filesystem image builder.",
	"emulator.machine":                  "Creates an in-process machine for the input's supported architecture, using native instruction execution and modeled Windows API callbacks. Instruction and memory limits bound execution; this is not a QEMU VM.",
	"emulator.plugin":                   "Wraps explicit mutable plugin state and its installation callback for emulator use. Keep checkpointed callback state here rather than hiding it in closures.",
	"emulator.x86":                      "Creates a bounded 32-bit x86 execution context from a PE image or raw code. Exposes guest registers, memory, hooks and snapshots; unsupported behavior returns structured stops rather than executing host code.",
	"error":                             "Stops evaluation with the supplied error message. Use testing.attempt when a caller needs to inspect an expected failure.",
	"filesystem.fat":                    "Parses an existing FAT volume into a filesystem view. Use fat12, fat16 or fat32 with a directory to construct a new volume.",
	"filesystem.fat12":                  "Builds a FAT12 volume from a directory with the requested size, boot metadata and file order. The returned file is an in-memory image, not a mounted filesystem.",
	"filesystem.fat16":                  "Builds a FAT16 volume from a directory, preserving supported attributes and requested boot metadata. Geometry and hidden-sector fields must match the surrounding disk layout.",
	"filesystem.fat32":                  "Builds a FAT32 volume from a directory and requested layout options. It produces a volume file for composition into a disk rather than writing or formatting a host device.",
	"filesystem.gpt":                    "With a file, parses GPT partition metadata; with a size, creates a partition-table builder. Populate the builder with partition contents to produce a complete disk layout.",
	"filesystem.host":                   "Exposes a host directory through the native filesystem backend. This is a host-path boundary, not an image parser or a portable replacement for an in-memory directory.",
	"filesystem.iso9660":                "Parses an ISO 9660 filesystem and exposes its directory tree and file views. It does not mount the image or copy its contents to the host.",
	"filesystem.mbr":                    "With a file, parses the MBR and partitions; with a disk size, creates a builder with optional boot code, signature and CHS geometry. Partition payloads remain caller-supplied.",
	"filesystem.ntfs":                   "Parses an NTFS volume when given a file, or builds one from a directory and size. Construction accepts explicit NTFS generation, boot metadata, log and upcase data so older NT layouts need not inherit modern defaults.",
	"filesystem.udf":                    "Parses a UDF filesystem into directory and file views. Reads resolve the filesystem's on-disk structures without mounting it.",
	"filesystem.vhdx":                   "Parses a VHDX container and exposes its logical disk contents. This unwraps the virtual-disk format; parse the returned disk's partitions/filesystems separately.",
	"firmware.acpi_compatible_id":       "Builds a complete SSDT file that assigns an ACPI compatible ID to the selected device. The output includes the ACPI header and checksum and can be supplied directly to qemu.acpi_table.",
	"firmware.acpi_table":               "Wraps an ACPI table body with the requested signature, revision and OEM/creator identifiers, computing its checksum. Returns a table file for use by a VM backend.",
	"help":                              "Prints runtime help for a value, or an overview of available globals when no value is supplied. Returns None and does not modify the inspected value.",
	"hex":                               "Formats an integer as signed, 0x-prefixed hexadecimal text with optional digit padding. For file, string or bytes input, returns the raw bytes as unprefixed hexadecimal text; width applies only to integers.",
	"html.escape":                       "Escapes special characters in text for HTML output. This is text escaping, not sanitization of an existing HTML document.",
	"html.unescape":                     "Decodes HTML character references in a string. It does not parse or validate markup.",
	"image.compare":                     "Compares decoded images and returns difference measurements using the specified per-pixel threshold. Pixel differences alone are not proof that a guest application launched successfully.",
	"image.info":                        "Decodes image metadata and returns dimensions and format information within input and pixel-count bounds.",
	"image.pixel":                       "Returns the color of one decoded image pixel at x,y. Coordinates must be inside the image; input size and decoded pixel limits apply.",
	"json.decode":                       "Parses bounded JSON input into Starlark dictionaries, lists and scalar values. Invalid JSON produces an error.",
	"json.encode":                       "Serializes a supported Starlark value as JSON text. Values that have no JSON representation fail rather than being stringified implicitly.",
	"mirror_file":                       "Opens a cached download or tries the supplied mirror URLs, checking the requested size and SHA-256 when supplied. The cache and key identify persistent native-backend storage; the result is a file, not extracted contents.",
	"open":                              "Opens a host-backed file for reading through the native storage backend. This is an explicit host-path boundary; portable format APIs consume the returned file.",
	"path.base":                         "Returns the last component of a logical path. It operates on path text and does not access the filesystem.",
	"path.clean":                        "Normalizes a logical path, resolving separators and dot components into the library's absolute-path form. It does not resolve symlinks or check host existence.",
	"path.dir":                          "Returns the containing directory of a logical path. This is lexical path manipulation, not a filesystem lookup.",
	"path.ext":                          "Returns the final filename extension, including its leading dot, or an empty string when none exists.",
	"path.from_windows":                 "Converts a Windows-style path into the library's logical slash-separated path representation. It does not translate it into a host path or access a drive.",
	"path.join":                         "Joins logical path components and normalizes the result. The operation is independent of the host operating system's path rules.",
	"qemu.acpi_table":                   "Creates a QEMU backend descriptor for an ACPI table file. The table is supplied through the backend when the VM starts.",
	"qemu.audiodev":                     "Creates a QEMU audio-backend descriptor from its name and properties. It is configuration data; creating it does not start audio or launch QEMU.",
	"qemu.backend":                      "Creates a QEMU implementation of the portable VMM backend with selected machine, acceleration, devices and transport policies. A separate vmm.start call launches the guest.",
	"qemu.chardev":                      "Creates a QEMU character-device backend descriptor from a backend name and properties. Use it in qemu.backend configuration.",
	"qemu.device":                       "Creates a QEMU device descriptor from a device model and properties. This is backend-specific configuration, not an already-running device.",
	"qemu.extension":                    "Returns the QEMU-specific control extension for an existing VM, including QMP/HMP and block statistics. Use portable VM methods when backend-specific control is unnecessary.",
	"qemu.netdev":                       "Creates a QEMU network-backend descriptor with the supplied properties. It does not independently create a host network interface.",
	"qemu.option":                       "Creates a supported QEMU command-line option descriptor. The backend validates and translates it at launch; it is not a shell command.",
	"regexp.compile":                    "Compiles a regular expression into a reusable matching object. Invalid patterns fail at compilation rather than at the first match.",
	"renvo.cc":                          "Compiles virtual C/C++ sources with the in-process Renvo toolchain for the selected target. Returns a compiledModule containing success/diagnostic information and virtual output bytes.",
	"renvo.go":                          "Compiles a virtual Go source tree with Renvo for the selected target. Returns compilation status and outputs without invoking a host Go compiler.",
	"renvo.make":                        "Evaluates supported Renvo make recipes against a virtual source tree and rebuilds their outputs in memory. output selects the desired binary relative to the Makefile; no host make process is launched.",
	"repl":                              "Enters the interactive Starlark prompt using the current runtime. Useful for retaining parsed inputs or a VM while running bounded experiments.",
	"runtime.stats":                     "Returns a snapshot of runtime resource statistics for diagnostics and benchmarking. Counters describe the running runtime, not just one image recipe.",
	"stdout":                            "Writes the supplied value to the runtime's standard output and returns None. It does not create a named file.",
	"testing.attempt":                   "Calls a function with supplied positional and keyword arguments and captures success or failure in an ok/value/error record. It does not roll back side effects performed before an error.",
	"testing.module":                    "Loads a module label and returns its globals as a dictionary. Used by the portable test runner to discover tests through the normal module loader.",
	"url.path_escape":                   "Percent-encodes text for use as one URL path segment. It is not query-string encoding or whole-URL normalization.",
	"url.path_unescape":                 "Decodes percent escapes in URL path text. Malformed escape sequences produce an error.",
	"vmm.backends":                      "Lists the VMM backends registered in this runtime and their advertised capabilities. Availability depends on the runtime's backend implementations.",
	"vmm.channel":                       "Describes a named VM byte channel of the requested kind. required determines whether lack of backend support is a validation failure.",
	"vmm.disk":                          "Describes a guest disk or optical medium backed by a file or block device, including bus, unit and write/snapshot policy. It does not boot or materialize the source.",
	"vmm.display":                       "Describes the requested guest display mode and whether support is mandatory. This is part of a portable machine specification.",
	"vmm.machine":                       "Creates a portable machine specification from architecture, memory, CPUs, storage, networking and channels. It does not start a VM.",
	"vmm.network":                       "Describes a named guest network connection and whether its requested kind is required. The selected backend implements the transport.",
	"vmm.start":                         "Validates a machine specification against a backend and starts a VM. Returns the live VM handle used for input, screenshots, events and lifecycle control.",
	"vmm.validate":                      "Checks whether a backend can implement a machine specification and its required capabilities without launching it. Use this before committing to a boot experiment.",
	"web.file":                          "Builds an HTTP response that serves a file, optionally with a download name, status and headers. Constructing the response does not start a web server.",
	"web.redirect":                      "Builds an HTTP redirect response with a Location header and selected redirect status. It does not follow the redirect.",
	"web.response":                      "Builds an HTTP response from body, status and headers for the web runtime to send.",
	"web.zip":                           "Builds a downloadable ZIP response for a directory in a supplied virtual filesystem. Packaging is handled in-process rather than by a host archiver.",
	"windows.assembly_manifest":         "Parses an assembly manifest XML value into identity attribute records and declared file records, including hashes and hash algorithms. It does not install a side-by-side assembly or verify those hashes.",
	"windows.catalog_hash":              "Computes the Windows catalog membership hash of a file. For PE inputs this uses the format's Authenticode hashing rules rather than a plain whole-file digest.",
	"windows.catalog_members":           "Reads a PKCS#7 catalog and returns its member digest byte strings. Extracting membership does not verify the catalog signature or establish certificate trust.",
	"windows.certificate":               "Parses one DER X.509 certificate and returns its DER bytes, subject, issuer, SHA-1 fingerprint and a subject/issuer-equality flag named self_signed. That flag is not cryptographic signature verification.",
	"windows.clone_file_entries":        "Copies a path-to-metadata dictionary and each entry dictionary, preserving insertion order. The two dictionary layers are independently mutable; file sources and other field values remain shared and are not read.",
	"windows.creg_compare":              "Compares two Windows 9x CREG registry files structurally and returns a difference report. This avoids treating different physical record layouts as necessarily different registry contents.",
	"windows.creg_from_patches":         "Constructs a Windows 9x CREG registry file from a name, value patches and optional key records. generation selects the intended Windows 9x layout; this is not an NT REGF hive writer.",
	"windows.creg_keys":                 "Returns the key paths represented by a Windows 9x CREG registry file as lists of path components. Empty keys can therefore be preserved independently of value patches.",
	"windows.creg_patches":              "Converts values in a Windows 9x CREG registry file into declarative registry patch dictionaries. Use creg_keys as well when reconstructing empty keys.",
	"windows.csp_registrations":         "Derives CryptoAPI provider-registration arguments from a 32-bit provider DLL without assigning registry paths or defaults. strict=False returns an empty list for unrecognized registration code; malformed input still fails. The provider is not executed.",
	"windows.empty_event_log":           "Constructs a valid empty legacy Windows event-log file of the requested size. This creates an EVT-format starting state, not an EVTX log.",
	"windows.event_log":                 "Parses legacy EVT or supported EVTX event-log input into event records. The format is detected from the file; this does not query the host's event-log service.",
	"windows.font_names":                "Extracts full font-name strings from supported OpenType/TrueType files, including collections. Returns a list of names without installing or rendering the font.",
	"windows.hive":                      "Parses an NT REGF registry hive and returns a read-only key/value inspection object. Use hive_from_patches to construct a hive and patch_hive to produce an edited copy.",
	"windows.hive_from_patches":         "Builds an NT registry hive from declarative value patches and optional key records. format controls the supported on-disk generation; security and key metadata remain caller-supplied policy.",
	"windows.hive_keys":                 "Enumerates an NT hive's key paths, optionally including key metadata. This preserves keys that have no values when exporting a hive for reconstruction.",
	"windows.hive_log":                  "Constructs the transaction-log companion for the supplied NT hive. The result is a new file; it does not replay a host registry log.",
	"windows.hive_patches":              "Exports an NT hive's values as declarative patches. raw requests raw value representations, useful when preserving types or bytes that should not be interpreted as text.",
	"windows.hives_from_inf":            "Builds registry hives from setup INF data with optional TXTSETUP context, extra inputs and patches. format selects the hive generation; the function does not boot Windows or execute setup.",
	"windows.inf":                       "Parses a Windows INF file into section and entry data, with helpers for install sections and registry patches. This is declarative inspection, not execution of every installer directive.",
	"windows.inf_patches":               "Converts a selected INF registry section into patches for the named hive. Returns modifications for later construction rather than changing an existing hive.",
	"windows.internet_shortcut":         "Builds InternetShortcut (.url) bytes for a URL with optional icon location and index. It creates the shortcut contents but does not fetch or open the URL.",
	"windows.kd":                        "Creates a Windows kernel-debugging protocol session over an existing byte channel. The session exposes packets, events, context and memory operations, bounded by the configured protocol limits.",
	"windows.minidump":                  "Parses a Windows minidump into inspectable dump streams and associated metadata. It operates on the supplied file and does not attach to a live process.",
	"windows.module_sources":            "Indexes a path-to-source dictionary by normalized DLL basename without reading sources. Matching is case-insensitive, both slash styles are accepted, extensionless basenames gain .dll, and the first non-excluded match wins.",
	"windows.mof":                       "Parses Managed Object Format source into a structured document containing its declarations. Pass documents to wmi_repository to construct repository files; parsing alone does not register classes with a running service.",
	"windows.msc_snapins":               "Extracts snap-in identifiers referenced by an MMC console file. Use the identifiers to select registration metadata; the function does not launch MMC.",
	"windows.ne_fastboot":               "Constructs the Windows NE fast-boot binary and overlay from supplied modules, returning bin and overlay files. overlay_path is the guest-visible location to encode, not a host output path.",
	"windows.patch_hive":                "Applies declarative registry patches to an NT hive and returns a new file, optionally replacing the root name. `keys` lists registry paths to create without adding values; existing keys and their values remain intact. This preserves the source hive's layout, including legacy REGF 1.1 cells. The input hive is not edited in place.",
	"windows.pdb":                       "Parses a PDB symbol file with bounded stream sizes. Exposes identity and symbols, including lookup of the nearest symbol to an RVA; symbol parsing does not download files automatically.",
	"windows.pe":                        "Creates a lazy inspection object for a PE32 or PE32+ file. Metadata and data share an owned immutable snapshot; read uses RVAs, while patch returns a separate modified file.",
	"windows.pe32_executable":           "Links a labeled section, fixups and optional imports into a minimal PE32 executable. The caller supplies instruction bytes and policy; the builder lays out headers, RVAs and imports and checks fixup bounds.",
	"windows.pkcs7_certificates":        "Extracts distinct embedded DER certificates from PKCS#7/CMS input, including legacy catalogs. Returns certificate records; extraction is deliberately separate from signature or trust verification.",
	"windows.reactos_record":            "Encodes a named ReactOS binary-record kind from declarative fields. Layout and field validation stay in Go while values and operating-system policy remain with the caller.",
	"windows.registration_expand":       "Expands percent-delimited registration variables in replacement-dictionary order, uppercase token then lowercase token, for at most four passes. Unknown tokens remain unchanged and non-string inputs pass through; this is not general case-insensitive environment expansion.",
	"windows.registry_children":         "Selects direct children from a self-registration registry-state dictionary. values=True selects direct values; otherwise it derives immediate subkeys, without changing the input or recursively returning descendants.",
	"windows.registry_partition":        "Splits a self-registration registry-state dictionary into selected and retained dictionaries for a hive subtree. values selects the value-identity layout; ordering and payload identity are preserved, and neither result aliases the input dictionary.",
	"windows.selfreg_patches":           "Derives registry patches from supported self-registration resources in a PE file or windows.pe object, using module for path substitutions. It does not emulate DllRegisterServer; use the self-registration policy/runner for runtime effects.",
	"windows.setver":                    "Returns a SETVER driver image with the named executable's reported DOS version added or updated. The original source remains unchanged and maximum bounds the processed image.",
	"windows.shortcut":                  "Builds Windows Shell Link (.lnk) bytes for a target with optional arguments, working directory, description and icon metadata. It serializes a shortcut; it does not resolve or launch its target on the host.",
	"windows.symbol_server":             "Retrieves a symbol file from a symbol-server layout using its name and identity key, with optional PDB GUID/age validation. maximum and timeout bound the download; windows.pdb parses the result.",
	"windows.utf16_strings":             "Scans a file for printable UTF-16LE strings meeting the minimum length. Returns extracted strings rather than decoding the entire file as text.",
	"windows.win9x_vxd_library":         "Builds a Windows 9x VxD library from a base and supplied members, excluding requested names. Returns the constructed file rather than installing drivers.",
	"windows.win9x_vxd_library_members": "Lists the member names contained in a Windows 9x VxD library. It provides inventory without writing member files to the host.",
	"windows.win9x_vxd_unpack":          "Decodes the supported compressed Windows 9x VxD container into an unpacked file. The result can be inspected or rebuilt without a host conversion tool.",
	"windows.wmi_repository":            "Either parses supplied repository files or constructs repository files from parsed MOF documents; exactly one input mode is required. Construction uses default_namespace and server_name to resolve repository identities without running WMI.",
	"write":                             "Writes a binary value to the named host output file, subject to max_bytes. This materializes an explicit output; use in-memory files to connect construction stages.",
}

var nativeStarlarkAdditionalSignatures = map[string]string{
	"archive.cab":                 "archive.cab(file, cache=True) -> cab",
	"archive.wim":                 "archive.wim(file) -> wim",
	"archive.zip":                 "archive.zip(file) -> zip",
	"binary.annotate":             "binary.annotate(file, attrs) -> file",
	"binary.bits":                 "binary.bits(value, order='msb') -> bit reader",
	"binary.builder":              "binary.builder(capacity=0, limit=512MiB) -> binary.builder",
	"binary.concat":               "binary.concat(parts) -> file",
	"binary.cursor":               "binary.cursor(value, offset=0) -> binary.cursor",
	"binary.decode":               "binary.decode(value, encoding, maximum=512MiB) -> bytes",
	"binary.encode":               "binary.encode(value, encoding='utf8', nul=False) -> bytes",
	"binary.extents":              "binary.extents(size, extents) -> file",
	"binary.layout":               "binary.layout(format, names=None) -> binary.layout",
	"binary.replace":              "binary.replace(value, old, new, count=-1, maximum=512MiB) -> bytes",
	"binary.strings":              "binary.strings(value, encoding='ascii', minimum=4, maximum=64MiB) -> list[string]",
	"binary.text":                 "binary.text(value, encoding='utf8', nul=False, maximum=16MiB) -> string",
	"binary.view":                 "binary.view(value, offset=0, size=None) -> byte_view",
	"clock.unix":                  "clock.unix() -> int",
	"clock.utc":                   "clock.utc(timestamp) -> dict",
	"crypto.aes":                  "crypto.aes(key, value, decrypt=False, mode='cbc', iv=None) -> bytes",
	"crypto.checksum":             "crypto.checksum(algorithm, value) -> int",
	"crypto.constant_time_equal":  "crypto.constant_time_equal(left, right) -> bool",
	"crypto.des":                  "crypto.des(key, value, decrypt=False, iv=None) -> bytes",
	"crypto.deterministic":        "crypto.deterministic(seed, size, algorithm='sha256') -> bytes",
	"crypto.hash":                 "crypto.hash(algorithm, value) -> bytes",
	"crypto.hash_blocks":          "crypto.hash_blocks(algorithm, state, blocks) -> bytes",
	"crypto.hasher":               "crypto.hasher(algorithm) -> crypto.hasher",
	"crypto.hmac":                 "crypto.hmac(algorithm, key, value) -> bytes",
	"crypto.mod_exp":              "crypto.mod_exp(base, exponent, modulus, byte_order='big') -> bytes",
	"crypto.mod_inverse":          "crypto.mod_inverse(value, modulus) -> int|None",
	"crypto.mod_mul":              "crypto.mod_mul(left, right, modulus, byte_order='big') -> bytes",
	"crypto.random":               "crypto.random(size) -> bytes",
	"crypto.rc4":                  "crypto.rc4(key, value) -> bytes",
	"crypto.xtea":                 "crypto.xtea(key, value, decrypt=False, byte_order='big') -> bytes",
	"database.sqlite":             "database.sqlite(file, wal=None) -> SQLite database",
	"database.sqlite_build":       "database.sqlite_build(objects, page_size=4096, encoding=1, user_version=0, application_id=0) -> file",
	"emulator.machine":            "emulator.machine(image|code, architecture='auto', **architecture_options) -> emulator",
	"emulator.plugin":             "emulator.plugin(install, name='plugin', state=None, attrs=None) -> plugin",
	"filesystem.fat":              "filesystem.fat(file) -> FAT filesystem",
	"filesystem.fat32":            "filesystem.fat32(directory, size, boot_code=None, hidden_sectors=0, label='NO NAME', boot_stage_sector=14, file_order=[], directory_label=True, chs=None) -> file",
	"filesystem.host":             "filesystem.host(root) -> host filesystem",
	"filesystem.iso9660":          "filesystem.iso9660(file) -> ISO filesystem",
	"filesystem.udf":              "filesystem.udf(file) -> UDF filesystem",
	"filesystem.vhdx":             "filesystem.vhdx(file) -> VHDX disk",
	"html.escape":                 "html.escape(value) -> string",
	"html.unescape":               "html.unescape(value) -> string",
	"json.encode":                 "json.encode(value, indent=None) -> string",
	"path.from_windows":           "path.from_windows(path) -> string",
	"path.join":                   "path.join(*parts) -> string",
	"qemu.audiodev":               "qemu.audiodev(name, **properties) -> qemu_audiodev",
	"regexp.compile":              "regexp.compile(pattern) -> regexp",
	"testing.attempt":             "testing.attempt(callback, args=None, kwargs=None) -> record(ok, value, error)",
	"testing.module":              "testing.module(label) -> dict",
	"url.path_escape":             "url.path_escape(value) -> string",
	"url.path_unescape":           "url.path_unescape(value) -> string",
	"web.file":                    "web.file(file, name='download', status=200, headers={}) -> response",
	"web.redirect":                "web.redirect(location, status=303) -> response",
	"web.response":                "web.response(body='', status=200, headers={}) -> response",
	"web.zip":                     "web.zip(filesystem, path, name='download.zip') -> response",
	"windows.assembly_manifest":   "windows.assembly_manifest(value) -> record(identity, files)",
	"windows.certificate":         "windows.certificate(value) -> certificate record",
	"windows.clone_file_entries":  "windows.clone_file_entries(entries) -> dict",
	"windows.empty_event_log":     "windows.empty_event_log(size=5MiB) -> file",
	"windows.event_log":           "windows.event_log(file) -> list[dict]",
	"windows.font_names":          "windows.font_names(file) -> list[string]",
	"windows.hive":                "windows.hive(file) -> registry hive",
	"windows.hive_from_patches":   "windows.hive_from_patches(name, patches, keys=None, format=None) -> file",
	"windows.hive_keys":           "windows.hive_keys(file, metadata=False) -> list",
	"windows.hive_log":            "windows.hive_log(file) -> file",
	"windows.hive_patches":        "windows.hive_patches(file, raw=False) -> list[dict]",
	"windows.hives_from_inf":      "windows.hives_from_inf(inf, txtsetup=None, extra=None, patches=None, format=None) -> dict",
	"windows.inf":                 "windows.inf(file) -> INF",
	"windows.inf_patches":         "windows.inf_patches(inf, hive, section='AddReg') -> list[dict]",
	"windows.internet_shortcut":   "windows.internet_shortcut(url, icon_location='', icon_index=0) -> bytes",
	"windows.memory_image":        "windows.memory_image(file, ranges=None) -> windows.memory_image",
	"windows.minidump":            "windows.minidump(file) -> minidump",
	"windows.module_sources":      "windows.module_sources(files, exclude=[]) -> dict",
	"windows.mof":                 "windows.mof(value) -> MOF document",
	"windows.msc_snapins":         "windows.msc_snapins(file) -> list[string]",
	"windows.patch_hive":          "windows.patch_hive(file, patches, root_name='', keys=[]) -> file",
	"windows.pe":                  "windows.pe(file) -> windows.pe",
	"windows.pe32_executable":     "windows.pe32_executable(section, labels, fixups, imports=None, entry='entry', image_base=0x400000) -> bytes",
	"windows.pkcs7_certificates":  "windows.pkcs7_certificates(value) -> list[certificate record]",
	"windows.registration_expand": "windows.registration_expand(value, replacements) -> value",
	"windows.registry_children":   "windows.registry_children(entries, hive, key, values=False) -> dict",
	"windows.registry_partition":  "windows.registry_partition(entries, hive, key, values=False) -> tuple(selected, retained)",
	"windows.selfreg_patches":     "windows.selfreg_patches(file, module) -> list[dict]",
	"windows.shortcut":            "windows.shortcut(target, short_target='', description='', arguments='', working_dir='', icon_location='', icon_index=0, target_size=0, system_root='') -> bytes",
	"windows.utf16_strings":       "windows.utf16_strings(file, minimum=4) -> list[string]",
}

func nativeStarlarkDescription(name string) (string, error) {
	if doc := nativeStarlarkDescriptions[name]; strings.TrimSpace(doc) != "" {
		return doc, nil
	}
	codecName := strings.TrimPrefix(name, "binary.")
	reading := strings.HasPrefix(codecName, "read_")
	codecName = strings.TrimPrefix(codecName, "read_")
	if strings.HasPrefix(name, "binary.") {
		if codec, ok := binaryapi.ScalarCodecNamed(codecName); ok {
			kind := "unsigned integer"
			if codec.Signed {
				kind = "signed integer"
			}
			if codec.Float {
				kind = "IEEE-754 floating-point value"
			}
			order := "little-endian"
			if strings.HasSuffix(codecName, "be") {
				order = "big-endian"
			}
			if codec.Width == 1 {
				order = "single-byte"
			}
			if reading {
				return fmt.Sprintf("Reads a %d-bit %s from source at the byte offset, using %s encoding. Returns the decoded scalar without advancing a cursor; a truncated read fails.", codec.Width*8, kind, order), nil
			}
			return fmt.Sprintf("Encodes a %d-bit %s as %d bytes in %s order. Returns new bytes; integer inputs outside the codec's range fail rather than silently truncating.", codec.Width*8, kind, codec.Width, order), nil
		}
	}
	return "", fmt.Errorf("native operation %s has no description", name)
}
